_extends: .github

repository:
  name: slack-roulette
  description: Slack bot that auto-assigns and pings teams and/or groups channel threads.
  homepage: https://github.com/bjd2385/slack-roulette

  # A comma-separated list of topics to set on the repository
  topics: python, slack, roulette, chat, threads
  private: false
